### ISSUE TITLE
Simplify environment.yml to minimal set of packages required

### ISSUE THREAD

**Issue by ericmjl** [a-r-j/graphein#23]
# Issue

Currently `environment.yml` and `ubuntu_environment.yml` are duplicates of one another, and could be simplified into a single file that uniquely specifies environment dependencies.

# Proposal

I'd like to propose unifying the two environment spec files into an `environment-dev.yml` file, which only specifies the minimal set of packages necessary for development/hacking on graphein. Deployment onto PyPI and conda forge later can allow for installation with dependencies automatically pulled in. This would be in tandem with the removal of the current `*environment.yml` files. 

A proposed starter environment spec could be:

```yaml
name: graphein-dev
channels:
- conda-forge
dependencies:
- python=3.8
- biopandas
- pandas
- networkx
- numpy
```

Conversion to DGL/PyTorch/JAX can be enabled once the library of code has been rewritten.
